async-only: true
bail: false
check-leaks: true
color: true
delay: false
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - ts
full-trace: false
recursive: true
require:
  - 'ts-node/register'
  - 'src/test/Globals.ts'
retries: 0
sort: false
spec: src/test/**/*.ts
timeout: 10000
reporter: mocha-multi-reporters
reporter-options: configFile=config.json
# ui: mocha-typescript
globals: 'allure'
