name: Tests

on:
  push:
    branches: [master, tests]
  pull_request:
    branches: [master]

jobs:
  autotests:
    name: Run tests and generate Allure Report
    strategy:
      matrix:
        node: ['14']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Run Test
        run: yarn test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: gh-pages
          path: gh-pages
          subfolder: reports

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: gh-pages/allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with: 
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          commit_message: 'tests: update'
          force_orphan: true
